In [20]:
import numpy as np
import pandas as pd

from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_score, recall_score, accuracy_score, confusion_matrix

df_userdata = pd.read_csv('../assets/userdata_min_40_v4.csv')

df_userdata = df_userdata.drop(df_userdata.columns[0:11],axis =1 )
df_userdata = df_userdata.drop(df_userdata.columns[-1],axis =1 )

df_userdata

kokosmelk  water  chilivlokken  gemalen kaneel  sjalot  knoflook  \
0            0      0             1               1       1         1   
1            0      0             0               0       1         1   
2            0      1             0               0       1         1   
3            0      0             0               0       0         1   
4            0      0             0               0       0         1   
..         ...    ...           ...             ...     ...       ...   
595          0      0             0               0       1         1   
596          0      1             0               0       0         1   
597          0      0             0               0       0         1   
598          0      0             0               0       1         1   
599          0      0             0               1       0         1   

     rode peper  zout  vastkokende aardappel  zoete aardappel  ...  \
0             0     1                      0                0  ...   
1             0     0                      1                0  ...   
2             0     1                      0                0  ...   
3             0     1                      0                0  ...   
4             0     0                      1                0  ...   
..          ...   ...                    ...              ...  ...   
595           0     0                      0                0  ...   
596           0     0                      0                0  ...   
597           0     0                      0                0  ...   
598           1     0                      0                0  ...   
599           0     0                      0                0  ...   

     (arachide)olie  tomatenblokjes  zoete puntpaprika  (olijf)olie  \
0                 0               0                  0            0   
1                 0               0                  0            0   
2                 0               0                  0            0   
3                 0               0                  0            0   
4                 0               0                  0            0   
..              ...             ...                ...          ...   
595               1               0                  1            0   
596               0               0                  0            0   
597               0               0                  1            0   
598               0               1                  0            1   
599               0               1                  0            1   

     kruimige aardappelen  magere gerookte spekreepjes  takje rozemarijn  \
0                       0                            0                 1   
1                       0                            0                 0   
2                       0                            1                 0   
3                       1                            0                 0   
4                       0                            0                 0   
..                    ...                          ...               ...   
595                     0                            0                 0   
596                     0                            0                 0   
597                     0                            0                 0   
598                     0                            0                 0   
599                     0                            0                 1   

     boter  aardappelen      kitchen  
0        0            0        frans  
1        0            0        frans  
2        0            0        frans  
3        1            0        frans  
4        0            0        frans  
..     ...          ...          ...  
595      0            0  mediterraan  
596      0            0  mediterraan  
597      0            0  mediterraan  
598      0            0  mediterraan  
599      0            0  mediterraan  

[600 rows x 174 columns]

In [21]:
for keuken in range(len(df_userdata)):
    
    if df_userdata['kitchen'].iloc[keuken] == 'thais':
        df_userdata['kitchen'].iloc[keuken] = 0
    elif df_userdata['kitchen'].iloc[keuken] == 'aziatisch':
        df_userdata['kitchen'].iloc[keuken] = 1
    elif df_userdata['kitchen'].iloc[keuken] == 'frans':
        df_userdata['kitchen'].iloc[keuken] = 2
    elif df_userdata['kitchen'].iloc[keuken] == 'indonesisch':
        df_userdata['kitchen'].iloc[keuken] = 3
    elif df_userdata['kitchen'].iloc[keuken] == 'hollands':
        df_userdata['kitchen'].iloc[keuken] = 4
    elif df_userdata['kitchen'].iloc[keuken] == 'italiaans':
        df_userdata['kitchen'].iloc[keuken] = 5
    elif df_userdata['kitchen'].iloc[keuken] == 'mexicaans':
        df_userdata['kitchen'].iloc[keuken] = 6
    elif df_userdata['kitchen'].iloc[keuken] == 'amerikaans':
        df_userdata['kitchen'].iloc[keuken] = 7
    elif df_userdata['kitchen'].iloc[keuken] == 'mediterraan':
        df_userdata['kitchen'].iloc[keuken] = 8
    
df_userdata.iloc[32]

C:\Users\Milan\AppData\Local\Temp\ipykernel_7752\2273157519.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_userdata['kitchen'].iloc[keuken] = 2
C:\Users\Milan\AppData\Local\Temp\ipykernel_7752\2273157519.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_userdata['kitchen'].iloc[keuken] = 1
C:\Users\Milan\AppData\Local\Temp\ipykernel_7752\2273157519.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_userdata['kitchen']

kokosmelk                      0
water                          1
chilivlokken                   0
gemalen kaneel                 0
sjalot                         0
                              ..
magere gerookte spekreepjes    0
takje rozemarijn               0
boter                          0
aardappelen                    0
kitchen                        2
Name: 32, Length: 174, dtype: object

In [22]:
y= df_userdata['kitchen']
X = df_userdata.drop('kitchen', axis = 1)

y=y.astype('int')

X_main, X_test, y_main, y_test = train_test_split(X, y, test_size = 0.2, random_state=42, stratify=y)
X_train, X_val, y_train, y_val = train_test_split(X_main, y_main, test_size = 0.25, random_state=42, stratify=y_main)
X_test

kokosmelk  water  chilivlokken  gemalen kaneel  sjalot  knoflook  \
267          0      0             0               0       0         0   
129          1      1             0               0       0         1   
463          0      0             0               0       0         1   
393          0      0             0               0       0         1   
427          0      0             0               0       0         1   
..         ...    ...           ...             ...     ...       ...   
32           0      1             0               0       0         1   
545          0      0             0               0       0         1   
586          0      1             0               1       1         1   
305          0      1             0               0       0         1   
95           0      0             0               0       1         1   

     rode peper  zout  vastkokende aardappel  zoete aardappel  ...  \
267           0     0                      1                0  ...   
129           1     1                      0                0  ...   
463           0     0                      0                0  ...   
393           0     1                      0                0  ...   
427           0     1                      0                0  ...   
..          ...   ...                    ...              ...  ...   
32            0     0                      0                1  ...   
545           1     0                      0                0  ...   
586           0     0                      0                0  ...   
305           0     0                      0                0  ...   
95            0     0                      1                0  ...   

     kippenbouillon van tablet  (arachide)olie  tomatenblokjes  \
267                          0               0               0   
129                          0               1               0   
463                          0               0               0   
393                          0               1               1   
427                          1               0               0   
..                         ...             ...             ...   
32                           0               0               1   
545                          0               0               1   
586                          0               0               0   
305                          0               1               0   
95                           0               0               1   

     zoete puntpaprika  (olijf)olie  kruimige aardappelen  \
267                  0            1                     0   
129                  0            0                     0   
463                  0            0                     0   
393                  0            0                     0   
427                  0            0                     0   
..                 ...          ...                   ...   
32                   0            1                     0   
545                  0            0                     0   
586                  0            1                     0   
305                  0            0                     0   
95                   0            0                     0   

     magere gerookte spekreepjes  takje rozemarijn  boter  aardappelen  
267                            0                 0      0            0  
129                            0                 0      0            0  
463                            0                 0      0            0  
393                            0                 0      0            0  
427                            0                 0      0            0  
..                           ...               ...    ...          ...  
32                             0                 0      0            0  
545                            0                 0      1            0  
586                            0                 0      0            0  
305                            

In [23]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_proba = model.predict(X_val)
y_proba

array([2, 4, 1, 5, 6, 5, 6, 5, 4, 5, 2, 6, 5, 6, 1, 1, 8, 5, 5, 2, 4, 1,
       2, 6, 5, 8, 6, 6, 8, 5, 6, 1, 8, 4, 5, 5, 5, 4, 4, 6, 1, 2, 5, 4,
       1, 2, 1, 8, 4, 4, 2, 2, 4, 2, 8, 5, 4, 8, 5, 6, 8, 1, 2, 4, 4, 2,
       5, 2, 6, 5, 1, 5, 5, 1, 6, 2, 4, 1, 4, 2, 5, 6, 5, 1, 2, 1, 2, 1,
       1, 8, 4, 6, 5, 1, 6, 5, 6, 2, 6, 1, 5, 8, 8, 5, 4, 6, 1, 1, 2, 2,
       6, 5, 4, 5, 8, 6, 4, 8, 6, 4])

In [24]:
print('Acc_score',accuracy_score(y_proba,y_val))
print('prec_score',precision_score(y_proba,y_val, average ='macro'))
print('rec_score',recall_score(y_proba,y_val, average ='macro'))

Acc_score 0.9333333333333333
prec_score 0.9333333333333335
rec_score 0.9488536155202821


In [25]:
from sklearn.metrics import roc_curve 

import matplotlib as plt


fpr, tpr, trhesholds = roc_curve(y_test, y_proba)


plt.plot([0.1],[0,1], 'k--')
plt.plot(fpr, tpr, 'b', label = 'AUC = %0.2f' % roc_auc)
plt.xlabel("False Positive Rate")
plt.ylabel('True Positive Rate')
plt.title('KneighborsClassifier ROC curve')
plt.show()

ValueError: multiclass format is not supported

In [26]:
param_dic ={'n_neighbors': np.arange(1,20),
           'metric':['euclidean','manhattan'],
           'weights': ['uniform', 'distance'],
           'leaf_size': np.arange(1,10)}


In [27]:
grid = GridSearchCV(model,param_dic, cv = 10)
grid.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'leaf_size': array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
                         'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19]),
                         'weights': ['uniform', 'distance']})

In [28]:
grid.best_params_

{'leaf_size': 1,
 'metric': 'euclidean',
 'n_neighbors': 5,
 'weights': 'distance'}

In [29]:
grid.best_estimator_

KNeighborsClassifier(leaf_size=1, metric='euclidean', weights='distance')

In [30]:
grid.best_score_

0.9694444444444443

In [31]:
model.score(X_val,y_val)

0.9333333333333333

In [32]:
from sklearn.metrics import precision_score, recall_score, accuracy_score
model = KNeighborsClassifier(leaf_size=1, metric='euclidean', weights='distance')

In [33]:
model.fit(X_train,y_train)
y_proba = model.predict(X_test)
y_proba

array([4, 1, 5, 6, 5, 6, 4, 8, 6, 6, 1, 2, 4, 1, 1, 1, 6, 5, 2, 6, 1, 4,
       8, 6, 5, 8, 8, 2, 4, 5, 6, 2, 6, 2, 6, 2, 6, 5, 5, 4, 2, 1, 4, 2,
       8, 1, 1, 1, 8, 5, 4, 2, 4, 2, 5, 8, 6, 6, 4, 1, 5, 4, 6, 8, 5, 1,
       6, 4, 5, 5, 5, 6, 4, 4, 2, 6, 1, 8, 8, 4, 2, 5, 2, 4, 1, 2, 8, 2,
       1, 5, 5, 8, 4, 6, 6, 5, 1, 5, 1, 4, 6, 4, 2, 5, 1, 2, 8, 5, 1, 1,
       5, 6, 2, 2, 5, 2, 5, 8, 6, 2])

In [34]:
print('Acc_score',accuracy_score(y_proba,y_test))
print('prec_score',precision_score(y_proba,y_test, average ='macro'))
print('rec_score',recall_score(y_proba,y_test, average ='macro'))

Acc_score 0.9333333333333333
prec_score 0.9333333333333335
rec_score 0.9403622693096377


In [35]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_proba))
print(classification_report(y_test, y_proba))

[[20  0  0  0  0  0]
 [ 0 20  0  0  0  0]
 [ 0  1 18  0  1  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 20  0]
 [ 0  0  1  4  1 14]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        20
           2       0.95      1.00      0.98        20
           4       0.95      0.90      0.92        20
           5       0.83      1.00      0.91        20
           6       0.91      1.00      0.95        20
           8       1.00      0.70      0.82        20

    accuracy                           0.93       120
   macro avg       0.94      0.93      0.93       120
weighted avg       0.94      0.93      0.93       120



In [36]:
model.score(X_test,y_test)

0.9333333333333333